a=input("enter your name:")
b=int(input("enter your contact number:"))
c=input("enter your e-mail :")
e=input("enter your birthdate:")
print("YOUR INFORMATION IS:")
print("name:",a)
print("contact no:",b)
print("e-mail:",c)
print("birthdate:",e)